// <auto-generated />
using System;
using BitcoinMarket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitcoinMarket.Migrations
{
    [DbContext(typeof(BitcoinMarketDbContext))]
    [Migration("20220703010138_deleteRestrictionsChanged")]
    partial class deleteRestrictionsChanged
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BitcoinMarket.Data.Models.PartialTrade", b =>
                {
                    b.Property<int>("PartialTradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuyTradeId")
                        .HasColumnType("int");

                    b.Property<int>("SellTradeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("PartialTradeId");

                    b.HasIndex("BuyTradeId");

                    b.HasIndex("SellTradeId");

                    b.ToTable("PartialTrades");
                });

            modelBuilder.Entity("BitcoinMarket.Data.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("FilledValue")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("IsBuy")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TransactionFinished")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionOwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionStarted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("ValueInBtc")
                        .HasPrecision(20, 10)
                        .HasColumnType("decimal(20,10)");

                    b.Property<decimal>("ValueInUsd")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionOwnerId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("BitcoinMarket.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BtcBalance")
                        .HasPrecision(20, 10)
                        .HasColumnType("decimal(20,10)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UsdBalance")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BitcoinMarket.Data.Models.PartialTrade", b =>
                {
                    b.HasOne("BitcoinMarket.Data.Trade", "BuyTrade")
                        .WithMany("PartialBuyTrades")
                        .HasForeignKey("BuyTradeId")
                        .IsRequired();

                    b.HasOne("BitcoinMarket.Data.Trade", "SellTrade")
                        .WithMany("PartialSellTrades")
                        .HasForeignKey("SellTradeId")
                        .IsRequired();

                    b.Navigation("BuyTrade");

                    b.Navigation("SellTrade");
                });

            modelBuilder.Entity("BitcoinMarket.Data.Trade", b =>
                {
                    b.HasOne("BitcoinMarket.Data.User", "TransactionOwner")
                        .WithMany("Trades")
                        .HasForeignKey("TransactionOwnerId")
                        .IsRequired();

                    b.Navigation("TransactionOwner");
                });

            modelBuilder.Entity("BitcoinMarket.Data.Trade", b =>
                {
                    b.Navigation("PartialBuyTrades");

                    b.Navigation("PartialSellTrades");
                });

            modelBuilder.Entity("BitcoinMarket.Data.User", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
